language: csharp
solution: dotnet-exec.sln
mono: none
dotnet: 3.1

stages:
    - test
    - publish

jobs:
  include:
    - stage: test
      if:  type = pull_request
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet test
    - stage: publish
      if: ( tag IS present ) AND (( branch = BUG-3-fix-travis-publish-error ))
      script:
        - VERSION=`git tag -l --sort committerdate | tail -1 | sed -E 's/-.+//' | sed -E 's/v//'`
        - VERSION=${VERSION:-'0.0.0'}
        - dotnet restore
        - dotnet pack -c Release /p:PackageVersion=$VERSION
        - dotnet nuget push .nupkg/*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
