language: csharp
solution: dotnet-exec.sln
mono: none
dotnet: 3.1

jobs:
  include:
    - stage: test
      if: type = push
      script:
        - dotnet restore
        - dotnet build
        - dotnet test
    - stage: publish
      if: 
        - branch = feature/init
        - type = push
      script:
        - dotnet restore
        - dotnet pack
        - dotnet nuget push .nupkg/*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
