language: csharp
solution: dotnet-exec.sln
mono: none
dotnet: 3.1

jobs:
  include:
    - stage: test
      script:
        - dotnet restore
        - dotnet build
        - dotnet test
    - stage: publish
      script:
        - dotnet restore
        - dotnet pack
        - dotnet nuget push .nupkg/*.nupkg --api-key $NUGET_API_KEY
